# QF 627 Programming and Computational Finance
## Problem Set 3 | `Questions`

> Hi Team 👋

> The current script is prepared to help you to exercise course content (But, again, do note that these are not assessment questions. They are for your exercise.)

> Some of the questions ask you to perform `reverse-engineering` 🧩. Instead of a question written in text format, you will be given the end results of some lines of code. Your task is to fill in the input cell with lines of code to create the output cell. Such a reverse-engineering exercise in computational programming will maximize your knowledge and skills in Computational Finance. 

> The questions below won’t be that difficult, as you have learned how to answer them from the lessons and the assigned readings. As you will notice from the questions, my intention is not just to give questions, but also to give additional learning pointers. I hope this helps 😊

##### First, let's do some quick exercise with stock prices data.

### <font color = green> Activation of necessary libraries. </font>

In [1]:
import numpy as np
import pandas as pd

import datetime

import warnings
warnings.filterwarnings("ignore")

### IMPORT your data (here, `apple_2024_stock`, `google_2024_stock`)

```python
# You may import data from the following URLs.

"http://www.talktoroh.com/s/apple_2024_stock.csv"

"http://www.talktoroh.com/s/google_2024_stock.csv"
```

In [28]:
df_apple =\
pd.read_csv("http://www.talktoroh.com/s/apple_2024_stock.csv").set_index("Date")

df_google =\
pd.read_csv("http://www.talktoroh.com/s/google_2024_stock.csv").set_index("Date")

### We will `re-organize` and `re-shape` stock data

> Let's concatenate data in multiple DataFrame objects

> Let's obtain Apple adjusted close data for July and August 2024.

In [29]:
df_apple

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-01-02,187.149994,188.440002,183.889999,185.639999,184.938217,82488700
2024-01-03,184.220001,185.880005,183.429993,184.250000,183.553467,58414500
2024-01-04,182.149994,183.089996,180.880005,181.910004,181.222321,71983600
2024-01-05,181.990005,182.759995,180.169998,181.179993,180.495087,62303300
2024-01-08,182.089996,185.600006,181.500000,185.559998,184.858521,59144500
...,...,...,...,...,...,...
2024-08-26,226.759995,227.279999,223.889999,227.179993,227.179993,30602200
2024-08-27,226.000000,228.850006,224.889999,228.029999,228.029999,35934600
2024-08-28,227.919998,229.860001,225.679993,226.490005,226.490005,38052200
2024-08-29,230.100006,232.919998,228.880005,229.789993,229.789993,51906300
2024-08-30,230.190002,230.399994,227.479996,229.000000,229.000000,52990800

In [30]:
df_apple.describe()

,Open,High,Low,Close,Adj Close,Volume
count,168.000000,168.000000,168.000000,168.000000,168.000000,1.680000e+02
mean,194.252380,196.172500,192.514821,194.389583,194.020255,6.168830e+07
std,20.554547,20.896348,20.132660,20.590587,20.712093,2.820863e+07
min,165.350006,166.399994,164.080002,165.000000,164.585999,3.029900e+07
25%,176.825001,178.592499,174.869999,178.139999,177.693039,4.596918e+07
50%,188.735001,190.285004,187.360001,188.740005,188.146538,5.353515e+07
75%,214.119995,216.962498,211.932499,214.252502,214.004791,6.862602e+07
max,236.479996,237.229996,233.089996,234.820007,234.548523,2.464214e+08

In [31]:
# apple_google =\
(
    pd.concat([df_apple, 
               df_google], 
              keys=['AAPL', 'GOOG'],
              axis=1)
)

                  AAPL                                                  \
                  Open        High         Low       Close   Adj Close
Date
2024-01-02  187.149994  188.440002  183.889999  185.639999  184.938217
2024-01-03  184.220001  185.880005  183.429993  184.250000  183.553467
2024-01-04  182.149994  183.089996  180.880005  181.910004  181.222321
2024-01-05  181.990005  182.759995  180.169998  181.179993  180.495087
2024-01-08  182.089996  185.600006  181.500000  185.559998  184.858521
...                ...         ...         ...         ...         ...
2024-08-26  226.759995  227.279999  223.889999  227.179993  227.179993
2024-08-27  226.000000  228.850006  224.889999  228.029999  228.029999
2024-08-28  227.919998  229.860001  225.679993  226.490005  226.490005
2024-08-29  230.100006  232.919998  228.880005  229.789993  229.789993
2024-08-30  230.190002  230.399994  227.479996  229.000000  229.000000

                            GOOG                                      \
              Volume        Open        High         Low       Close
Date
2024-01-02  82488700  138.550003  139.449997  136.479996  138.169998
2024-01-03  58414500  137.250000  139.630005  137.080002  138.919998
2024-01-04  71983600  138.419998  139.160004  136.350006  136.389999
2024-01-05  62303300  136.750000  137.160004  135.149994  135.729996
2024-01-08  59144500  136.289993  139.009995  136.259995  138.839996
...              ...         ...         ...         ...         ...
2024-08-26  30602200  166.380005  167.550003  164.460007  166.160004
2024-08-27  35934600  165.839996  166.440002  164.460007  164.679993
2024-08-28  38052200  165.039993  165.600006  161.529999  162.850006
2024-08-29  51906300  164.309998  165.970001  160.250000  161.779999
2024-08-30  52990800  162.619995  163.660004  161.690002  163.380005


             Adj Close    Volume
Date
2024-01-02  137.828705  23711200
2024-01-03  138.576859  24212100
2024-01-04  136.053101  27137700
2024-01-05  135.394745  22506000
2024-01-08  138.497055  21404000
...                ...       ...
2024-08-26  165.939804  14190400
2024-08-27  164.461761  11821900
2024-08-28  162.634201  16407400
2024-08-29  161.565613  19699800
2024-08-30  163.163498  22123800

[168 rows x 12 columns]

In [35]:
apple_07 =\
(
    df_apple.loc['2024-07-01':'2024-07-31']
)

In [40]:
apple_07[['Adj Close']].head()

             Adj Close
Date
2024-07-01  216.499405
2024-07-02  220.015335
2024-07-03  221.293854
2024-07-05  226.078308
2024-07-08  227.556610

             Adj Close
Date
2024-07-01  216.499405
2024-07-02  220.015335
2024-07-03  221.293854
2024-07-05  226.078308
2024-07-08  227.556610

In [41]:
apple_08 =\
(
    df_apple.loc['2024-08-01':'2024-08-31']
)

apple_08[['Adj Close']].head()

             Adj Close
Date
2024-08-01  218.107544
2024-08-02  219.605804
2024-08-05  209.028061
2024-08-06  206.990402
2024-08-07  209.577423

             Adj Close
Date
2024-08-01  218.107544
2024-08-02  219.605804
2024-08-05  209.028061
2024-08-06  206.990402
2024-08-07  209.577423

### Question 1-1. Please combine the first three rows of each of `apple_07` and `apple_08`

In [53]:
first3 = \
(
    pd.concat([apple_07['Adj Close'].iloc[:3], 
               apple_08['Adj Close'].iloc[:3]])
)

pd.DataFrame(first3)

             Adj Close
Date
2024-07-01  216.499405
2024-07-02  220.015335
2024-07-03  221.293854
2024-08-01  218.107544
2024-08-02  219.605804
2024-08-05  209.028061

             Adj Close
Date
2024-07-01  216.499405
2024-07-02  220.015335
2024-07-03  221.293854
2024-08-01  218.107544
2024-08-02  219.605804
2024-08-05  209.028061

#### Question 1-2. How would you extract only the 2021 August GOOGL values?

In [58]:
googl_08 =\
(
    df_google.loc['2024-08-01':'2024-08-31']
)

googl_08[['Adj Close']]

             Adj Close
Date
2024-08-01  170.533707
2024-08-02  166.439148
2024-08-05  159.038971
2024-08-06  158.080231
2024-08-07  158.729370
2024-08-08  161.815277
2024-08-09  163.453110
2024-08-12  162.074921
2024-08-13  163.942459
2024-08-14  160.157471
2024-08-15  161.086243
2024-08-16  162.744049
2024-08-19  166.449127
2024-08-20  166.958450
2024-08-21  165.630219
2024-08-22  163.582932
2024-08-23  165.400513
2024-08-26  165.939804
2024-08-27  164.461761
2024-08-28  162.634201
2024-08-29  161.565613
2024-08-30  163.163498

             Adj Close
Date
2024-08-01  170.533707
2024-08-02  166.439148
2024-08-05  159.038971
2024-08-06  158.080231
2024-08-07  158.729370
2024-08-08  161.815277
2024-08-09  163.453110
2024-08-12  162.074921
2024-08-13  163.942459
2024-08-14  160.157471
2024-08-15  161.086243
2024-08-16  162.744049
2024-08-19  166.449127
2024-08-20  166.958450
2024-08-21  165.630219
2024-08-22  163.582932
2024-08-23  165.400513
2024-08-26  165.939804
2024-08-27  164.461761
2024-08-28  162.634201
2024-08-29  161.565613
2024-08-30  163.163498

#### Question 1-3. Please concatenate the AAPL and GOOGL 2021 August stock data--there will be duplicate index labels

In [72]:
# df =\
(    
    pd.concat([apple_08['Adj Close'].iloc[:3], 
           googl_08['Adj Close'].iloc[:3]], 
           axis=0).to_frame()  # axis=1 for columns, axis=0 for rows
)

             Adj Close
Date
2024-08-01  218.107544
2024-08-02  219.605804
2024-08-05  209.028061
2024-08-01  170.533707
2024-08-02  166.439148
2024-08-05  159.038971

             Adj Close
Date
2024-08-01  218.107544
2024-08-02  219.605804
2024-08-05  209.028061
2024-08-01  170.533707
2024-08-02  166.439148
2024-08-05  159.038971

> Let's see the `two records for data of 2024-08-02`

In [75]:
df.loc['2024-08-02']

             Adj Close
Date
2024-08-02  219.605804
2024-08-02  166.439148

             Adj Close
Date
2024-08-02  219.605804
2024-08-02  166.439148

#### Question 1-4. Please concatenate to show a specification of the stock tickers being part of the index. This will help disambiguate the duplicate dates using a hierarchal index.

In [85]:
# apple_google =\
(
    pd.concat([apple_08['Adj Close'].iloc[:3], 
               googl_08['Adj Close'].iloc[:3]], 
              keys=['AAPL', 'GOOGL'],
              axis=0)
              .to_frame()
)

                   Adj Close
      Date
AAPL  2024-08-01  218.107544
      2024-08-02  219.605804
      2024-08-05  209.028061
GOOGL 2024-08-01  170.533707
      2024-08-02  166.439148
      2024-08-05  159.038971

                   Adj Close
      Date
AAPL  2024-08-01  218.107544
      2024-08-02  219.605804
      2024-08-05  209.028061
GOOGL 2024-08-01  170.533707
      2024-08-02  166.439148
      2024-08-05  159.038971

> Let's extract just GOOGL values using `.loc`

In [87]:
apple_google.loc['GOOGL',:]

             Adj Close
Date
2024-08-01  170.533707
2024-08-02  166.439148
2024-08-05  159.038971

             Adj Close
Date
2024-08-01  170.533707
2024-08-02  166.439148
2024-08-05  159.038971

#### Question 1-5. Let's show concatenation using two DataFrame's that each have two columns.  `pandas` will align the data in columns by the column names (labels)

In [88]:
pd.concat([df_apple[['Adj Close', 'Volume']], df_google[['Adj Close', 'Volume']]],
        #   keys=['AAPL', 'GOOGL'],
        #   axis=0
          )

             Adj Close    Volume
Date
2024-01-02  184.938217  82488700
2024-01-03  183.553467  58414500
2024-01-04  181.222321  71983600
2024-01-05  180.495087  62303300
2024-01-08  184.858521  59144500
...                ...       ...
2024-08-26  165.939804  14190400
2024-08-27  164.461761  11821900
2024-08-28  162.634201  16407400
2024-08-29  161.565613  19699800
2024-08-30  163.163498  22123800

[336 rows x 2 columns]

> Let's see concatenation with DataFrame objects that do not have the same set of columns.

> This will show pandas filling in `NaN` values.

In [89]:
pd.concat([df_apple[['Adj Close', 'Volume']], df_google[['Adj Close']]],
        #   keys=['AAPL', 'GOOGL'],
        #   axis=0
          )

             Adj Close      Volume
Date
2024-01-02  184.938217  82488700.0
2024-01-03  183.553467  58414500.0
2024-01-04  181.222321  71983600.0
2024-01-05  180.495087  62303300.0
2024-01-08  184.858521  59144500.0
...                ...         ...
2024-08-26  165.939804         NaN
2024-08-27  164.461761         NaN
2024-08-28  162.634201         NaN
2024-08-29  161.565613         NaN
2024-08-30  163.163498         NaN

[336 rows x 2 columns]

             Adj Close      Volume
Date
2024-01-02  184.938217  82488700.0
2024-01-03  183.553467  58414500.0
2024-01-04  181.222321  71983600.0
2024-01-05  180.495087  62303300.0
2024-01-08  184.858521  59144500.0
...                ...         ...
2024-08-26  165.939804         NaN
2024-08-27  164.461761         NaN
2024-08-28  162.634201         NaN
2024-08-29  161.565613         NaN
2024-08-30  163.163498         NaN

[336 rows x 2 columns]

### Question 2-1. Please perform an inner join on the DataFrame's since `google_a` does not have a Volume column, pandas will not include that column in the result.

In [90]:
apple_a = df_apple[['Adj Close', 'Volume']]
google_a = df_google[['Adj Close']]

pd.concat([apple_a, google_a],
          join='inner')

             Adj Close
Date
2024-01-02  184.938217
2024-01-03  183.553467
2024-01-04  181.222321
2024-01-05  180.495087
2024-01-08  184.858521
...                ...
2024-08-26  165.939804
2024-08-27  164.461761
2024-08-28  162.634201
2024-08-29  161.565613
2024-08-30  163.163498

[336 rows x 1 columns]

             Adj Close
Date
2024-01-02  184.938217
2024-01-03  183.553467
2024-01-04  181.222321
2024-01-05  180.495087
2024-01-08  184.858521
...                ...
2024-08-26  165.939804
2024-08-27  164.461761
2024-08-28  162.634201
2024-08-29  161.565613
2024-08-30  163.163498

[336 rows x 1 columns]

#### Question 2-2. Then, please concatenate along the rows, causing duplicate columns to be created in the result.

In [95]:
pd.concat([apple_a['Adj Close'], google_a],
          join='inner',
          axis=1
          )

             Adj Close   Adj Close
Date
2024-01-02  184.938217  137.828705
2024-01-03  183.553467  138.576859
2024-01-04  181.222321  136.053101
2024-01-05  180.495087  135.394745
2024-01-08  184.858521  138.497055
...                ...         ...
2024-08-26  227.179993  165.939804
2024-08-27  228.029999  164.461761
2024-08-28  226.490005  162.634201
2024-08-29  229.789993  161.565613
2024-08-30  229.000000  163.163498

[168 rows x 2 columns]

             Adj Close   Adj Close
Date
2024-01-02  184.938217  137.828705
2024-01-03  183.553467  138.576859
2024-01-04  181.222321  136.053101
2024-01-05  180.495087  135.394745
2024-01-08  184.858521  138.497055
...                ...         ...
2024-08-26  227.179993  165.939804
2024-08-27  228.029999  164.461761
2024-08-28  226.490005  162.634201
2024-08-29  229.789993  161.565613
2024-08-30  229.000000  163.163498

[168 rows x 2 columns]

#### Question 2-3. Let's concat along rows using two DataFrame objects with different number of rows. 

#### This demonstrates how NaN values will be filled in those rows for `apple` which only has three rows as compared to 5 for `google`

In [100]:
pd.concat([df_apple[['Adj Close', 'Volume']].iloc[:5], 
           df_google[['Adj Close', 'Volume']].iloc[:3]],
           keys=['AAPL', 'GOOGL'],
          join='outer',
          axis=1)

                  AAPL                 GOOGL
             Adj Close    Volume   Adj Close      Volume
Date
2024-01-02  184.938217  82488700  137.828705  23711200.0
2024-01-03  183.553467  58414500  138.576859  24212100.0
2024-01-04  181.222321  71983600  136.053101  27137700.0
2024-01-05  180.495087  62303300         NaN         NaN
2024-01-08  184.858521  59144500         NaN         NaN

                  AAPL                 GOOGL
             Adj Close    Volume   Adj Close      Volume
Date
2024-01-02  184.938217  82488700  137.828705  23711200.0
2024-01-03  183.553467  58414500  138.576859  24212100.0
2024-01-04  181.222321  71983600  136.053101  27137700.0
2024-01-05  180.495087  62303300         NaN         NaN
2024-01-08  184.858521  59144500         NaN         NaN

#### Question 2-4. You know that `inner join` can also be used `along this axis`. 

#### Please include rows with index labels that do not exist in both DataFrame objects

In [101]:
pd.concat([df_apple[['Adj Close', 'Volume']].iloc[:5], 
           df_google[['Adj Close', 'Volume']].iloc[:3]],
           keys=['AAPL', 'GOOGL'],
          join='inner',
          axis=1)

                  AAPL                 GOOGL
             Adj Close    Volume   Adj Close    Volume
Date
2024-01-02  184.938217  82488700  137.828705  23711200
2024-01-03  183.553467  58414500  138.576859  24212100
2024-01-04  181.222321  71983600  136.053101  27137700

                  AAPL                 GOOGL
             Adj Close    Volume   Adj Close    Volume
Date
2024-01-02  184.938217  82488700  137.828705  23711200
2024-01-03  183.553467  58414500  138.576859  24212100
2024-01-04  181.222321  71983600  136.053101  27137700

#### Question 2-5. Please ignore indexes and just concatenate the data and have the result have a default integer index

In [106]:
pd.concat([df_apple[['Adj Close']].iloc[:3], 
           df_google[['Adj Close']].iloc[:3]],
          join='inner',
          axis=0).reset_index(drop=True)

    Adj Close
0  184.938217
1  183.553467
2  181.222321
3  137.828705
4  138.576859
5  136.053101

    Adj Close
0  184.938217
1  183.553467
2  181.222321
3  137.828705
4  138.576859
5  136.053101

### `Now let's merging DataFrame objects`

In [110]:
df_apple['Adj Close'].reset_index()

           Date   Adj Close
0    2024-01-02  184.938217
1    2024-01-03  183.553467
2    2024-01-04  181.222321
3    2024-01-05  180.495087
4    2024-01-08  184.858521
..          ...         ...
163  2024-08-26  227.179993
164  2024-08-27  228.029999
165  2024-08-28  226.490005
166  2024-08-29  229.789993
167  2024-08-30  229.000000

[168 rows x 2 columns]

          Date   Adj Close
0   2024-01-02  184.938217
1   2024-01-03  183.553467
2   2024-01-04  181.222321
3   2024-01-05  180.495087
4   2024-01-08  184.858521
..         ...         ...
163 2024-08-26  227.179993
164 2024-08-27  228.029999
165 2024-08-28  226.490005
166 2024-08-29  229.789993
167 2024-08-30  229.000000

[168 rows x 2 columns]

### Question 3-1. Please merge the two DataFrame objects, so lets peek at the data to remind ourselves of what they contain.

###  `pandas` finds the columns in common, in this case Date, and merges on that column and adds a column for all the other columns in both DataFrames.

In [114]:
df_apple[['Adj Close', 'Volume']].reset_index().head()

         Date   Adj Close    Volume
0  2024-01-02  184.938217  82488700
1  2024-01-03  183.553467  58414500
2  2024-01-04  181.222321  71983600
3  2024-01-05  180.495087  62303300
4  2024-01-08  184.858521  59144500

        Date   Adj Close    Volume
0 2024-01-02  184.938217  82488700
1 2024-01-03  183.553467  58414500
2 2024-01-04  181.222321  71983600
3 2024-01-05  180.495087  62303300
4 2024-01-08  184.858521  59144500

#### Question 3-2. Please use the merge function to create the below.

In [133]:
# df_a =\
pd.merge(left=df_apple[['Adj Close']].reset_index(),
            right=df_apple[['Volume']].reset_index(),
            how='inner',
            on='Date',
            ).iloc[2:4].reset_index(drop=True)

         Date   Adj Close    Volume
0  2024-01-04  181.222321  71983600
1  2024-01-05  180.495087  62303300

        Date   Adj Close    Volume
0 2024-01-04  181.222321  71983600
1 2024-01-05  180.495087  62303300

#### Question 3-3. How would you create the below then?

In [136]:
pd.merge(
    left=df_google[['Adj Close']].reset_index().head(),
    right=df_a[['Date', 'Volume']],
    how='outer',
    on='Date'
)

         Date   Adj Close      Volume
0  2024-01-02  137.828705         NaN
1  2024-01-03  138.576859         NaN
2  2024-01-04  136.053101  71983600.0
3  2024-01-05  135.394745  62303300.0
4  2024-01-08  138.497055         NaN

        Date   Adj Close      Volume
0 2024-01-02  184.938217         NaN
1 2024-01-03  183.553467         NaN
2 2024-01-04  181.222321  71983600.0
3 2024-01-05  180.495087  62303300.0
4 2024-01-08  184.858521         NaN

### Let's do some `pivoting`

### Question 4-1. Please insert `Symbol` column before combining

In [ ]:
df_apple.insert(0, 'Symbol', 'AAPL')

,Symbol,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,184.938217,82488700
2024-01-03,AAPL,184.220001,185.880005,183.429993,184.250000,183.553467,58414500
2024-01-04,AAPL,182.149994,183.089996,180.880005,181.910004,181.222321,71983600
2024-01-05,AAPL,181.990005,182.759995,180.169998,181.179993,180.495087,62303300
2024-01-08,AAPL,182.089996,185.600006,181.500000,185.559998,184.858521,59144500
...,...,...,...,...,...,...,...
2024-08-26,AAPL,226.759995,227.279999,223.889999,227.179993,227.179993,30602200
2024-08-27,AAPL,226.000000,228.850006,224.889999,228.029999,228.029999,35934600
2024-08-28,AAPL,227.919998,229.860001,225.679993,226.490005,226.490005,38052200
2024-08-29,AAPL,230.100006,232.919998,228.880005,229.789993,229.789993,51906300
2024-08-30,AAPL,230.190002,230.399994,227.479996,229.000000,229.000000,52990800

In [145]:
df_google.insert(0, 'Symbol', 'GOOGL')

In [143]:
print(df_apple)

           Symbol        Open        High         Low       Close   Adj Close  \
Date
2024-01-02   AAPL  187.149994  188.440002  183.889999  185.639999  184.938217
2024-01-03   AAPL  184.220001  185.880005  183.429993  184.250000  183.553467
2024-01-04   AAPL  182.149994  183.089996  180.880005  181.910004  181.222321
2024-01-05   AAPL  181.990005  182.759995  180.169998  181.179993  180.495087
2024-01-08   AAPL  182.089996  185.600006  181.500000  185.559998  184.858521
...           ...         ...         ...         ...         ...         ...
2024-08-26   AAPL  226.759995  227.279999  223.889999  227.179993  227.179993
2024-08-27   AAPL  226.000000  228.850006  224.889999  228.029999  228.029999
2024-08-28   AAPL  227.919998  229.860001  225.679993  226.490005  226.490005
2024-08-29   AAPL  230.100006  232.919998  228.880005  229.789993  229.789993
2024-08-30   AAPL  230.190002  230.399994  227.479996  229.000000  229.000000

              Volume
Date
2024-01-02  82488700
2024-01-03  58414500
2024-01-04  71983600
2024-01-05  62303300
2024-01-08  59144500
...              ...
2024-08-26  30602200
2024-08-27  35934600
2024-08-28  38052200
2024-08-29  51906300
2024-08-30  52990800

[168 rows x 7 columns]

In [ ]:
df_apple

           Symbol        Open        High         Low       Close   Adj Close  \
Date
2024-01-02   AAPL  187.149994  188.440002  183.889999  185.639999  184.938217
2024-01-03   AAPL  184.220001  185.880005  183.429993  184.250000  183.553467
2024-01-04   AAPL  182.149994  183.089996  180.880005  181.910004  181.222321
2024-01-05   AAPL  181.990005  182.759995  180.169998  181.179993  180.495087
2024-01-08   AAPL  182.089996  185.600006  181.500000  185.559998  184.858521
...           ...         ...         ...         ...         ...         ...
2024-08-26   AAPL  226.759995  227.279999  223.889999  227.179993  227.179993
2024-08-27   AAPL  226.000000  228.850006  224.889999  228.029999  228.029999
2024-08-28   AAPL  227.919998  229.860001  225.679993  226.490005  226.490005
2024-08-29   AAPL  230.100006  232.919998  228.880005  229.789993  229.789993
2024-08-30   AAPL  230.190002  230.399994  227.479996  229.000000  229.000000

              Volume
Date
2024-01-02  82488700
2024-01-03  58414500
2024-01-04  71983600
2024-01-05  62303300
2024-01-08  59144500
...              ...
2024-08-26  30602200
2024-08-27  35934600
2024-08-28  38052200
2024-08-29  51906300
2024-08-30  52990800

[168 rows x 7 columns]
           Symbol        Open        High         Low       Close   Adj Close  \
Date
2024-01-02  GOOGL  138.550003  139.449997  136.479996  138.169998  137.828705
2024-01-03  GOOGL  137.250000  139.630005  137.080002  138.919998  138.576859
2024-01-04  GOOGL  138.419998  139.160004  136.350006  136.389999  136.053101
2024-01-05  GOOGL  136.750000  137.160004  135.149994  135.729996  135.394745
2024-01-08  GOOGL  136.289993  139.009995  136.259995  138.839996  138.497055
...           ...         ...         ...         ...         ...         ...
2024-08-26  GOOGL  166.380005  167.550003  164.460007  166.160004  165.939804
2024-08-27  GOOGL  165.839996  166.440002  164.460007  164.679993  164.461761
2024-08-28  GOOGL  165.039993  165.600006  161.529999  162.850006  162.634201
2024-08-29  GOOGL  164.309998  165.970001  160.250000  161.779999  161.565613
2024-08-30  GOOGL  162.619995  163.660004  161.690002  163.380005  163.163498

              Volume
Date
2024-01-02  23711200
2024-01-03  24212100
2024-01-04  27137700
2024-01-05  22506000
2024-01-08  21404000
...              ...
2024-08-26  14190400
2024-08-27  11821900
2024-08-28  16407400
2024-08-29  19699800
2024-08-30  22123800

[168 rows x 7 columns]

#### Question 4-2. Please concatenate the `Apple` and `Google` data index will consist of the Date column, which we will sort.

In [155]:
df =\
pd.concat([df_apple,
           df_google]).sort_index()

,Symbol,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,184.938217,82488700
2024-01-02,GOOGL,138.550003,139.449997,136.479996,138.169998,137.828705,23711200
2024-01-03,GOOGL,137.250000,139.630005,137.080002,138.919998,138.576859,24212100
2024-01-03,AAPL,184.220001,185.880005,183.429993,184.250000,183.553467,58414500
2024-01-04,AAPL,182.149994,183.089996,180.880005,181.910004,181.222321,71983600
...,...,...,...,...,...,...,...
2024-08-28,AAPL,227.919998,229.860001,225.679993,226.490005,226.490005,38052200
2024-08-29,GOOGL,164.309998,165.970001,160.250000,161.779999,161.565613,19699800
2024-08-29,AAPL,230.100006,232.919998,228.880005,229.789993,229.789993,51906300
2024-08-30,AAPL,230.190002,230.399994,227.479996,229.000000,229.000000,52990800
2024-08-30,GOOGL,162.619995,163.660004,161.690002,163.380005,163.163498,22123800

#### Question 4-3. Please pushes the index into a column and resets to a default integer index.

In [156]:
df =\
df.reset_index()

In [157]:
df.head()

,Date,Symbol,Open,High,Low,Close,Adj Close,Volume
0,2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,184.938217,82488700
1,2024-01-02,GOOGL,138.550003,139.449997,136.479996,138.169998,137.828705,23711200
2,2024-01-03,GOOGL,137.250000,139.630005,137.080002,138.919998,138.576859,24212100
3,2024-01-03,AAPL,184.220001,185.880005,183.429993,184.250000,183.553467,58414500
4,2024-01-04,AAPL,182.149994,183.089996,180.880005,181.910004,181.222321,71983600

,Date,Symbol,Open,High,Low,Close,Adj Close,Volume
0,2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,184.938217,82488700
1,2024-01-02,GOOGL,138.550003,139.449997,136.479996,138.169998,137.828705,23711200
2,2024-01-03,GOOGL,137.250000,139.630005,137.080002,138.919998,138.576859,24212100
3,2024-01-03,AAPL,184.220001,185.880005,183.429993,184.250000,183.553467,58414500
4,2024-01-04,AAPL,182.149994,183.089996,180.880005,181.910004,181.222321,71983600

#### Question 4-4. Please pivot Date into the Index, make the columns match the unique values in the Symbol column, and the values will be the AdjClose values

In [159]:
df.pivot(index='Date', columns='Symbol', values='Adj Close')

Symbol            AAPL       GOOGL
Date
2024-01-02  184.938217  137.828705
2024-01-03  183.553467  138.576859
2024-01-04  181.222321  136.053101
2024-01-05  180.495087  135.394745
2024-01-08  184.858521  138.497055
...                ...         ...
2024-08-26  227.179993  165.939804
2024-08-27  228.029999  164.461761
2024-08-28  226.490005  162.634201
2024-08-29  229.789993  161.565613
2024-08-30  229.000000  163.163498

[168 rows x 2 columns]

Symbol            AAPL       GOOGL
Date
2024-01-02  184.938217  137.828705
2024-01-03  183.553467  138.576859
2024-01-04  181.222321  136.053101
2024-01-05  180.495087  135.394745
2024-01-08  184.858521  138.497055
...                ...         ...
2024-08-26  227.179993  165.939804
2024-08-27  228.029999  164.461761
2024-08-28  226.490005  162.634201
2024-08-29  229.789993  161.565613
2024-08-30  229.000000  163.163498

[168 rows x 2 columns]

### Let's execute `stacking` and `unstacking`

### Question 5-1. Please stack the first level of columns into the index.

### Let's move AAPL and GOOGL into the index leaving a single colum which is the AdjClose values

In [161]:
df.pivot(index='Date', columns='Symbol', values='Adj Close').stack()

Date        Symbol
2024-01-02  AAPL      184.938217
            GOOGL     137.828705
2024-01-03  AAPL      183.553467
            GOOGL     138.576859
2024-01-04  AAPL      181.222321
                         ...
2024-08-28  GOOGL     162.634201
2024-08-29  AAPL      229.789993
            GOOGL     161.565613
2024-08-30  AAPL      229.000000
            GOOGL     163.163498
Length: 336, dtype: float64

Date        Symbol
2024-01-02  AAPL      184.938217
            GOOGL     137.828705
2024-01-03  AAPL      183.553467
            GOOGL     138.576859
2024-01-04  AAPL      181.222321
                         ...
2024-08-28  GOOGL     162.634201
2024-08-29  AAPL      229.789993
            GOOGL     161.565613
2024-08-30  AAPL      229.000000
            GOOGL     163.163498
Length: 336, dtype: float64

> Using `.loc` we can retrieve close values by specifying both the date and ticker

In [173]:
print(df.pivot(index='Date', columns='Symbol', values='Adj Close').stack().loc['2024-01-04','AAPL'])

181.22232055664065

181.22232055664062

#### Question 5-2. Please lookup on just the date, which will give us two values one each for AAPL and GOOGL.

In [174]:
print(df.pivot(index='Date', columns='Symbol', values='Adj Close').stack().loc['2024-01-04'])

Symbol
AAPL     181.222321
GOOGL    136.053101
dtype: float64

Symbol
AAPL     181.222321
GOOGL    136.053101
dtype: float64

> Let's have a look at all values for the GOOGL symbol

In [177]:
df.pivot(index='Date', columns='Symbol', values='Adj Close')['GOOGL']

Date
2024-01-02    137.828705
2024-01-03    138.576859
2024-01-04    136.053101
2024-01-05    135.394745
2024-01-08    138.497055
                 ...
2024-08-26    165.939804
2024-08-27    164.461761
2024-08-28    162.634201
2024-08-29    161.565613
2024-08-30    163.163498
Name: GOOGL, Length: 168, dtype: float64

Date
2024-01-02    137.828705
2024-01-03    138.576859
2024-01-04    136.053101
2024-01-05    135.394745
2024-01-08    138.497055
                 ...
2024-08-26    165.939804
2024-08-27    164.461761
2024-08-28    162.634201
2024-08-29    161.565613
2024-08-30    163.163498
Length: 168, dtype: float64

#### Question 5-3. Please pivot the last level of the index back into a column

In [181]:
df.pivot(index='Date', columns='Symbol', values='Adj Close').iloc[:3]

Symbol            AAPL       GOOGL
Date
2024-01-02  184.938217  137.828705
2024-01-03  183.553467  138.576859
2024-01-04  181.222321  136.053101

Symbol            AAPL       GOOGL
Date
2024-01-02  184.938217  137.828705
2024-01-03  183.553467  138.576859
2024-01-04  181.222321  136.053101

### Now, let's do some `melting`

### Question 6-1. Please use `melt` to make id_vars of Date and Symbol, making the column names the variable and the for each the value

In [188]:
df.melt(
    id_vars=['Date', 'Symbol']
).head()

         Date Symbol variable       value
0  2024-01-02   AAPL     Open  187.149994
1  2024-01-02  GOOGL     Open  138.550003
2  2024-01-03  GOOGL     Open  137.250000
3  2024-01-03   AAPL     Open  184.220001
4  2024-01-04   AAPL     Open  182.149994

        Date Symbol variable       value
0 2024-01-02   AAPL     Open  187.149994
1 2024-01-02  GOOGL     Open  138.550003
2 2024-01-03  GOOGL     Open  137.250000
3 2024-01-03   AAPL     Open  184.220001
4 2024-01-04   AAPL     Open  182.149994

#### Question 6-2. Please extract the values for the data for Google on 2024-08-23

In [189]:
df =\
df.melt(
    id_vars=['Date', 'Symbol']
)

In [193]:
df[(df.Symbol == 'GOOGL') & (df.Date == '2024-08-23')]

            Date Symbol   variable         value
325   2024-08-23  GOOGL       Open  1.647200e+02
661   2024-08-23  GOOGL       High  1.661800e+02
997   2024-08-23  GOOGL        Low  1.638300e+02
1333  2024-08-23  GOOGL      Close  1.656200e+02
1669  2024-08-23  GOOGL  Adj Close  1.654005e+02
2005  2024-08-23  GOOGL     Volume  1.395570e+07

           Date Symbol   variable         value
325  2024-08-23  GOOGL       Open  1.647200e+02
661  2024-08-23  GOOGL       High  1.661800e+02
997  2024-08-23  GOOGL        Low  1.638300e+02
1333 2024-08-23  GOOGL      Close  1.656200e+02
1669 2024-08-23  GOOGL  Adj Close  1.654005e+02
2005 2024-08-23  GOOGL     Volume  1.395570e+07

### Let's do some grouping and aggregation

##### To do so, we will do some splitting first.

> Let's construct a DataFrame to demonstrate splitting

### Question 7-1. Please extract from combined the Symbol and AdjClose, and reset the index

In [212]:
df_apple

,Symbol,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,184.938217,82488700
2024-01-03,AAPL,184.220001,185.880005,183.429993,184.250000,183.553467,58414500
2024-01-04,AAPL,182.149994,183.089996,180.880005,181.910004,181.222321,71983600
2024-01-05,AAPL,181.990005,182.759995,180.169998,181.179993,180.495087,62303300
2024-01-08,AAPL,182.089996,185.600006,181.500000,185.559998,184.858521,59144500
...,...,...,...,...,...,...,...
2024-08-26,AAPL,226.759995,227.279999,223.889999,227.179993,227.179993,30602200
2024-08-27,AAPL,226.000000,228.850006,224.889999,228.029999,228.029999,35934600
2024-08-28,AAPL,227.919998,229.860001,225.679993,226.490005,226.490005,38052200
2024-08-29,AAPL,230.100006,232.919998,228.880005,229.789993,229.789993,51906300
2024-08-30,AAPL,230.190002,230.399994,227.479996,229.000000,229.000000,52990800

In [367]:
df =\
(
    pd.concat([df_apple[['Symbol', 'Adj Close']].reset_index(), 
            df_google[['Symbol', 'Adj Close']].reset_index()],axis=0).sort_values(by=['Date'])
) 
# 
# .pivot(index='Date', columns='Symbol', values='Adj Close').melt()

In [368]:
df=\
df.reset_index(drop=True)

          Date Symbol   Adj Close
0   2024-01-02   AAPL  184.938217
1   2024-01-02  GOOGL  137.828705
2   2024-01-03  GOOGL  138.576859
3   2024-01-03   AAPL  183.553467
4   2024-01-04   AAPL  181.222321
..         ...    ...         ...
331 2024-08-28   AAPL  226.490005
332 2024-08-29  GOOGL  161.565613
333 2024-08-29   AAPL  229.789993
334 2024-08-30   AAPL  229.000000
335 2024-08-30  GOOGL  163.163498

[336 rows x 3 columns]

#### Question 7-2. Please add two columns, year and month, using the year and month portions of the data as integers

In [369]:
df.Date.dtype

dtype('O')

In [370]:
df['Date'].apply(lambda x: int(x[:4]))

0      2024
1      2024
2      2024
3      2024
4      2024
       ...
331    2024
332    2024
333    2024
334    2024
335    2024
Name: Date, Length: 336, dtype: int64

In [371]:
df.insert(1, 'Year', df['Date'].apply(lambda x: int(x[:4])))
df

           Date  Year Symbol   Adj Close
0    2024-01-02  2024   AAPL  184.938217
1    2024-01-02  2024  GOOGL  137.828705
2    2024-01-03  2024  GOOGL  138.576859
3    2024-01-03  2024   AAPL  183.553467
4    2024-01-04  2024   AAPL  181.222321
..          ...   ...    ...         ...
331  2024-08-28  2024   AAPL  226.490005
332  2024-08-29  2024  GOOGL  161.565613
333  2024-08-29  2024   AAPL  229.789993
334  2024-08-30  2024   AAPL  229.000000
335  2024-08-30  2024  GOOGL  163.163498

[336 rows x 4 columns]

          Date  Year Symbol   Adj Close
0   2024-01-02  2024   AAPL  184.938217
1   2024-01-02  2024  GOOGL  137.828705
2   2024-01-03  2024  GOOGL  138.576859
3   2024-01-03  2024   AAPL  183.553467
4   2024-01-04  2024   AAPL  181.222321
..         ...   ...    ...         ...
331 2024-08-28  2024   AAPL  226.490005
332 2024-08-29  2024  GOOGL  161.565613
333 2024-08-29  2024   AAPL  229.789993
334 2024-08-30  2024   AAPL  229.000000
335 2024-08-30  2024  GOOGL  163.163498

[336 rows x 4 columns]

In [372]:
df.insert(2, 'Month', df['Date'].apply(lambda x: int(x[5:7])))
df

           Date  Year  Month Symbol   Adj Close
0    2024-01-02  2024      1   AAPL  184.938217
1    2024-01-02  2024      1  GOOGL  137.828705
2    2024-01-03  2024      1  GOOGL  138.576859
3    2024-01-03  2024      1   AAPL  183.553467
4    2024-01-04  2024      1   AAPL  181.222321
..          ...   ...    ...    ...         ...
331  2024-08-28  2024      8   AAPL  226.490005
332  2024-08-29  2024      8  GOOGL  161.565613
333  2024-08-29  2024      8   AAPL  229.789993
334  2024-08-30  2024      8   AAPL  229.000000
335  2024-08-30  2024      8  GOOGL  163.163498

[336 rows x 5 columns]

          Date  Year  Month Symbol   Adj Close
0   2024-01-02  2024      1   AAPL  184.938217
1   2024-01-02  2024      1  GOOGL  137.828705
2   2024-01-03  2024      1  GOOGL  138.576859
3   2024-01-03  2024      1   AAPL  183.553467
4   2024-01-04  2024      1   AAPL  181.222321
..         ...   ...    ...    ...         ...
331 2024-08-28  2024      8   AAPL  226.490005
332 2024-08-29  2024      8  GOOGL  161.565613
333 2024-08-29  2024      8   AAPL  229.789993
334 2024-08-30  2024      8   AAPL  229.000000
335 2024-08-30  2024      8  GOOGL  163.163498

[336 rows x 5 columns]

In [373]:
df['Date'] = df['Date'].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d'))

> Let's group by the Symbol column

In [374]:
df.groupby(['Symbol'])

> The groupby object has a property groups, which shows how all rows will in mapped into the groups.

> The type of this object is a python dict

In [375]:
type(df.groupby(['Symbol']).groups)

pandas.io.formats.printing.PrettyDict

pandas.io.formats.printing.PrettyDict

> Let's show the mappings of rows to groups

In [376]:
df.groupby(['Symbol']).groups

{'AAPL': [0, 3, 4, 6, 8, 11, 13, 15, 17, 19, 21, 23, 24, 26, 29, 31, 32, 34, 36, 38, 41, 43, 44, 47, 49, 50, 52, 55, 56, 59, 61, 63, 65, 66, 69, 70, 73, 75, 76, 79, 80, 83, 85, 86, 89, 90, 92, 95, 97, 98, 101, 102, 104, 106, 108, 111, 113, 115, 117, 118, 120, 123, 125, 127, 129, 130, 133, 134, 136, 138, 140, 143, 145, 147, 149, 151, 152, 155, 156, 159, 161, 162, 165, 166, 169, 171, 172, 175, 177, 179, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, ...], 'GOOGL': [1, 2, 5, 7, 9, 10, 12, 14, 16, 18, 20, 22, 25, 27, 28, 30, 33, 35, 37, 39, 40, 42, 45, 46, 48, 51, 53, 54, 57, 58, 60, 62, 64, 67, 68, 71, 72, 74, 77, 78, 81, 82, 84, 87, 88, 91, 93, 94, 96, 99, 100, 103, 105, 107, 109, 110, 112, 114, 116, 119, 121, 122, 124, 126, 128, 131, 132, 135, 137, 139, 141, 142, 144, 146, 148, 150, 153, 154, 157, 158, 160, 163, 164, 167, 168, 170, 173, 174, 176, 178, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, ...]}

{'AAPL': [0, 3, 4, 6, 8, 11, 13, 15, 17, 19, 21, 23, 24, 26, 29, 31, 32, 34, 36, 38, 41, 43, 44, 47, 49, 50, 52, 55, 56, 59, 61, 63, 65, 66, 69, 70, 73, 75, 76, 79, 80, 83, 85, 86, 89, 90, 92, 95, 97, 98, 101, 102, 104, 106, 108, 111, 113, 115, 117, 118, 120, 123, 125, 127, 129, 130, 133, 134, 136, 138, 140, 143, 145, 147, 149, 151, 152, 155, 156, 159, 161, 162, 165, 166, 169, 171, 172, 175, 177, 179, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, ...], 'GOOGL': [1, 2, 5, 7, 9, 10, 12, 14, 16, 18, 20, 22, 25, 27, 28, 30, 33, 35, 37, 39, 40, 42, 45, 46, 48, 51, 53, 54, 57, 58, 60, 62, 64, 67, 68, 71, 72, 74, 77, 78, 81, 82, 84, 87, 88, 91, 93, 94, 96, 99, 100, 103, 105, 107, 109, 110, 112, 114, 116, 119, 121, 122, 124, 126, 128, 131, 132, 135, 137, 139, 141, 142, 144, 146, 148, 150, 153, 154, 157, 158, 160, 163, 164, 167, 168, 170, 173, 174, 176, 178, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, ...]}

> Yes, this reports the number of groups that resulted from the grouping

In [377]:
df.groupby(['Symbol'])

(2, 2)

### Question 8-1. Please create a function that prints the contents of a group. You might want to look at the outputs below for hints.

###  When you execute your function you should see the following results.

In [378]:
df.groupby(['Symbol']).groups

{'AAPL': [0, 3, 4, 6, 8, 11, 13, 15, 17, 19, 21, 23, 24, 26, 29, 31, 32, 34, 36, 38, 41, 43, 44, 47, 49, 50, 52, 55, 56, 59, 61, 63, 65, 66, 69, 70, 73, 75, 76, 79, 80, 83, 85, 86, 89, 90, 92, 95, 97, 98, 101, 102, 104, 106, 108, 111, 113, 115, 117, 118, 120, 123, 125, 127, 129, 130, 133, 134, 136, 138, 140, 143, 145, 147, 149, 151, 152, 155, 156, 159, 161, 162, 165, 166, 169, 171, 172, 175, 177, 179, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, ...], 'GOOGL': [1, 2, 5, 7, 9, 10, 12, 14, 16, 18, 20, 22, 25, 27, 28, 30, 33, 35, 37, 39, 40, 42, 45, 46, 48, 51, 53, 54, 57, 58, 60, 62, 64, 67, 68, 71, 72, 74, 77, 78, 81, 82, 84, 87, 88, 91, 93, 94, 96, 99, 100, 103, 105, 107, 109, 110, 112, 114, 116, 119, 121, 122, 124, 126, 128, 131, 132, 135, 137, 139, 141, 142, 144, 146, 148, 150, 153, 154, 157, 158, 160, 163, 164, 167, 168, 170, 173, 174, 176, 178, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, ...]}

In [379]:
for k, v in df.groupby(['Symbol']).groups.items():
    print(k)
    print(df.loc[v].head())

AAPL
        Date  Year  Month Symbol   Adj Close
0 2024-01-02  2024      1   AAPL  184.938217
3 2024-01-03  2024      1   AAPL  183.553467
4 2024-01-04  2024      1   AAPL  181.222321
6 2024-01-05  2024      1   AAPL  180.495087
8 2024-01-08  2024      1   AAPL  184.858521
GOOGL
        Date  Year  Month Symbol   Adj Close
1 2024-01-02  2024      1  GOOGL  137.828705
2 2024-01-03  2024      1  GOOGL  138.576859
5 2024-01-04  2024      1  GOOGL  136.053101
7 2024-01-05  2024      1  GOOGL  135.394745
9 2024-01-08  2024      1  GOOGL  138.497055

In [380]:
def print_groups(groupings):
    for k, v in df.groupby(groupings).groups.items():
        print(k)
        print(df.loc[v].head())

In [381]:
print_groups(['Symbol'])

AAPL
        Date  Year  Month Symbol   Adj Close
0 2024-01-02  2024      1   AAPL  184.938217
3 2024-01-03  2024      1   AAPL  183.553467
4 2024-01-04  2024      1   AAPL  181.222321
6 2024-01-05  2024      1   AAPL  180.495087
8 2024-01-08  2024      1   AAPL  184.858521
GOOGL
        Date  Year  Month Symbol   Adj Close
1 2024-01-02  2024      1  GOOGL  137.828705
2 2024-01-03  2024      1  GOOGL  138.576859
5 2024-01-04  2024      1  GOOGL  136.053101
7 2024-01-05  2024      1  GOOGL  135.394745
9 2024-01-08  2024      1  GOOGL  138.497055

AAPL
                  Date  Year Month Symbol   Adj Close
0  2024-01-02 00:00:00  2024     1   AAPL  184.938217
3  2024-01-03 00:00:00  2024     1   AAPL  183.553467
4  2024-01-04 00:00:00  2024     1   AAPL  181.222321
6  2024-01-05 00:00:00  2024     1   AAPL  180.495087
8  2024-01-08 00:00:00  2024     1   AAPL  184.858521
GOOGL
                  Date  Year Month Symbol   Adj Close
1  2024-01-02 00:00:00  2024     1  GOOGL  137.828705
2  2024-01-03 00:00:00  2024     1  GOOGL  138.576859
5  2024-01-04 00:00:00  2024     1  GOOGL  136.053101
7  2024-01-05 00:00:00  2024     1  GOOGL  135.394745
9  2024-01-08 00:00:00  2024     1  GOOGL  138.497055

> .size will tell us the count of items in each group

In [382]:
df.groupby(['Symbol']).size()

Symbol
AAPL     168
GOOGL    168
dtype: int64

Symbol
AAPL     168
GOOGL    168
dtype: int64

#### Question 8-2. As you know, a specific group can be retrieved using .get_group() which returns a DataFrame representing the specified group. Please execute so that you can have the output below.

In [383]:
df.groupby(['Symbol']).get_group('AAPL')

          Date  Year  Month Symbol   Adj Close
0   2024-01-02  2024      1   AAPL  184.938217
3   2024-01-03  2024      1   AAPL  183.553467
4   2024-01-04  2024      1   AAPL  181.222321
6   2024-01-05  2024      1   AAPL  180.495087
8   2024-01-08  2024      1   AAPL  184.858521
..         ...   ...    ...    ...         ...
327 2024-08-26  2024      8   AAPL  227.179993
329 2024-08-27  2024      8   AAPL  228.029999
331 2024-08-28  2024      8   AAPL  226.490005
333 2024-08-29  2024      8   AAPL  229.789993
334 2024-08-30  2024      8   AAPL  229.000000

[168 rows x 5 columns]

          Date  Year  Month Symbol   Adj Close
0   2024-01-02  2024      1   AAPL  184.938217
3   2024-01-03  2024      1   AAPL  183.553467
4   2024-01-04  2024      1   AAPL  181.222321
6   2024-01-05  2024      1   AAPL  180.495087
8   2024-01-08  2024      1   AAPL  184.858521
..         ...   ...    ...    ...         ...
327 2024-08-26  2024      8   AAPL  227.179993
329 2024-08-27  2024      8   AAPL  228.029999
331 2024-08-28  2024      8   AAPL  226.490005
333 2024-08-29  2024      8   AAPL  229.789993
334 2024-08-30  2024      8   AAPL  229.000000

[168 rows x 5 columns]

#### Question 8-3. Please group by three different fields (`Symbol`, `Year`, `Month`) and print the result

In [384]:
print_groups(['Symbol', 'Year', 'Month'])

('AAPL', 2024, 1)
        Date  Year  Month Symbol   Adj Close
0 2024-01-02  2024      1   AAPL  184.938217
3 2024-01-03  2024      1   AAPL  183.553467
4 2024-01-04  2024      1   AAPL  181.222321
6 2024-01-05  2024      1   AAPL  180.495087
8 2024-01-08  2024      1   AAPL  184.858521
('AAPL', 2024, 2)
         Date  Year  Month Symbol   Adj Close
43 2024-02-01  2024      2   AAPL  186.153625
44 2024-02-02  2024      2   AAPL  185.147430
47 2024-02-05  2024      2   AAPL  186.970505
49 2024-02-06  2024      2   AAPL  188.584381
50 2024-02-07  2024      2   AAPL  188.693970
('AAPL', 2024, 3)
         Date  Year  Month Symbol   Adj Close
83 2024-03-01  2024      3   AAPL  179.209229
85 2024-03-04  2024      3   AAPL  174.660660
86 2024-03-05  2024      3   AAPL  169.693161
89 2024-03-06  2024      3   AAPL  168.695648
90 2024-03-07  2024      3   AAPL  168.575958
('AAPL', 2024, 4)
          Date  Year  Month Symbol   Adj Close
123 2024-04-01  2024      4   AAPL  169.603378
125 2024-04-02  2024      4   AAPL  168.416351
127 2024-04-03  2024      4   AAPL  169.224319
129 2024-04-04  2024      4   AAPL  168.396423
130 2024-04-05  2024      4   AAPL  169.154495
('AAPL', 2024, 5)
          Date  Year  Month Symbol   Adj Close
166 2024-05-01  2024      5   AAPL  168.875214
169 2024-05-02  2024      5   AAPL  172.595840
171 2024-05-03  2024      5   AAPL  182.919876
172 2024-05-06  2024      5   AAPL  181.254089
175 2024-05-07  2024      5   AAPL  181.942322
('AAPL', 2024, 6)
          Date  Year  Month Symbol   Adj Close
211 2024-06-03  2024      6   AAPL  193.805664
212 2024-06-04  2024      6   AAPL  194.125305
214 2024-06-05  2024      6   AAPL  195.643539
216 2024-06-06  2024      6   AAPL  194.255142
219 2024-06-07  2024      6   AAPL  196.662369
('AAPL', 2024, 7)
          Date  Year  Month Symbol   Adj Close
249 2024-07-01  2024      7   AAPL  216.499405
251 2024-07-02  2024      7   AAPL  220.015335
253 2024-07-03  2024      7   AAPL  221.293854
254 2024-07-05  2024      7   AAPL  226.078308
256 2024-07-08  2024      7   AAPL  227.556610
('AAPL', 2024, 8)
          Date  Year  Month Symbol   Adj Close
292 2024-08-01  2024      8   AAPL  218.107544
295 2024-08-02  2024      8   AAPL  219.605804
297 2024-08-05  2024      8   AAPL  209.028061
299 2024-08-06  2024      8   AAPL  206.990402
300 2024-08-07  2024      8   AAPL  209.577423
('GOOGL', 2024, 1)
        Date  Year  Month Symbol   Adj Close
1 2024-01-02  2024      1  GOOGL  137.828705
2 2024-01-03  2024      1  GOOGL  138.576859
5 2024-01-04  2024      1  GOOGL  136.053101
7 2024-01-05  2024      1  GOOGL  135.394745
9 2024-01-08  2024      1  GOOGL  138.497055
('GOOGL', 2024, 2)
         Date  Year  Month Symbol   Adj Close
42 2024-02-01  2024      2  GOOGL  140.811340
45 2024-02-02  2024      2  GOOGL  142.028320
46 2024-02-05  2024      2  GOOGL  143.325089
48 2024-02-06  2024      2  GOOGL  143.744080
51 2024-02-07  2024      2  GOOGL  145.180511
('GOOGL', 2024, 3)
         Date  Year  Month Symbol   Adj Close
82 2024-03-01  2024      3  GOOGL  136.801254
84 2024-03-04  2024      3  GOOGL  133.020630
87 2024-03-05  2024      3  GOOGL  132.342300
88 2024-03-06  2024      3  GOOGL  131.075424
91 2024-03-07  2024      3  GOOGL  134.048080
('GOOGL', 2024, 4)
          Date  Year  Month Symbol   Adj Close
122 2024-04-01  2024      4  GOOGL  155.105942
124 2024-04-02  2024      4  GOOGL  154.178223
126 2024-04-03  2024      4  GOOGL  154.537338
128 2024-04-04  2024      4  GOOGL  150.158188
131 2024-04-05  2024      4  GOOGL  152.123322
('GOOGL', 2024, 5)
          Date  Year  Month Symbol   Adj Close
167 2024-05-01  2024      5  GOOGL  163.455246
168 2024-05-02  2024      5  GOOGL  166.208435
170 2024-05-03  2024      5  GOOGL  166.826904
173 2024-05-06  2024      5  GOOGL  167.684799
174 2024-05-07  2024      5  GOOGL  170.826996
('GOOGL', 2024, 6)
          Date  Year  Month Symbol   Adj Close
210 2024-06-03  2024      6  GOOGL  172.742264
213 2024-06-04  2024      6  GOOGL  173.360718
215 2024-06-05  2024      6  GOOGL  174.976746
217 2024-06-06  2024      6  GOOGL  176.293457
218 2024-06-07  2024      6  GOOGL  174.029083
('GOOGL', 2024, 7)
          Date  Year  Month Symbol   Adj Close
248 2024-07-01  2024      7  GOOGL  182.747513
250 2024-07-02  2024      7  GOOGL  184.994522
252 2024-07-03  2024      7  GOOGL  185.573761
255 2024-07-05  2024      7  GOOGL  190.347427
257 2024-07-08  2024      7  GOOGL  188.779495
('GOOGL', 2024, 8)
          Date  Year  Month Symbol   Adj Close
293 2024-08-01  2024      8  GOOGL  170.533707
294 2024-08-02  2024      8  GOOGL  166.439148
296 2024-08-05  2024      8  GOOGL  159.038971
298 2024-08-06  2024      8  GOOGL  158.080231
301 2024-08-07  2024      8  GOOGL  158.729370

('AAPL', 2024, 1)
        Date  Year  Month Symbol   Adj Close
0 2024-01-02  2024      1   AAPL  184.938217
3 2024-01-03  2024      1   AAPL  183.553467
4 2024-01-04  2024      1   AAPL  181.222321
6 2024-01-05  2024      1   AAPL  180.495087
8 2024-01-08  2024      1   AAPL  184.858521
('AAPL', 2024, 2)
         Date  Year  Month Symbol   Adj Close
43 2024-02-01  2024      2   AAPL  186.153625
44 2024-02-02  2024      2   AAPL  185.147430
47 2024-02-05  2024      2   AAPL  186.970505
49 2024-02-06  2024      2   AAPL  188.584381
50 2024-02-07  2024      2   AAPL  188.693970
('AAPL', 2024, 3)
         Date  Year  Month Symbol   Adj Close
83 2024-03-01  2024      3   AAPL  179.209229
85 2024-03-04  2024      3   AAPL  174.660660
86 2024-03-05  2024      3   AAPL  169.693161
89 2024-03-06  2024      3   AAPL  168.695648
90 2024-03-07  2024      3   AAPL  168.575958
('AAPL', 2024, 4)
          Date  Year  Month Symbol   Adj Close
123 2024-04-01  2024      4   AAPL  169.603378
125 2024-04-02  2024      4   AAPL  168.416351
127 2024-04-03  2024      4   AAPL  169.224319
129 2024-04-04  2024      4   AAPL  168.396423
130 2024-04-05  2024      4   AAPL  169.154495
('AAPL', 2024, 5)
          Date  Year  Month Symbol   Adj Close
166 2024-05-01  2024      5   AAPL  168.875214
169 2024-05-02  2024      5   AAPL  172.595840
171 2024-05-03  2024      5   AAPL  182.919876
172 2024-05-06  2024      5   AAPL  181.254089
175 2024-05-07  2024      5   AAPL  181.942322
('AAPL', 2024, 6)
          Date  Year  Month Symbol   Adj Close
211 2024-06-03  2024      6   AAPL  193.805664
212 2024-06-04  2024      6   AAPL  194.125305
214 2024-06-05  2024      6   AAPL  195.643539
216 2024-06-06  2024      6   AAPL  194.255142
219 2024-06-07  2024      6   AAPL  196.662369
('AAPL', 2024, 7)
          Date  Year  Month Symbol   Adj Close
249 2024-07-01  2024      7   AAPL  216.499405
251 2024-07-02  2024      7   AAPL  220.015335
253 2024-07-03  2024      7   AAPL  221.293854
254 2024-07-05  2024      7   AAPL  226.078308
256 2024-07-08  2024      7   AAPL  227.556610
('AAPL', 2024, 8)
          Date  Year  Month Symbol   Adj Close
292 2024-08-01  2024      8   AAPL  218.107544
295 2024-08-02  2024      8   AAPL  219.605804
297 2024-08-05  2024      8   AAPL  209.028061
299 2024-08-06  2024      8   AAPL  206.990402
300 2024-08-07  2024      8   AAPL  209.577423
('GOOGL', 2024, 1)
        Date  Year  Month Symbol   Adj Close
1 2024-01-02  2024      1  GOOGL  137.828705
2 2024-01-03  2024      1  GOOGL  138.576859
5 2024-01-04  2024      1  GOOGL  136.053101
7 2024-01-05  2024      1  GOOGL  135.394745
9 2024-01-08  2024      1  GOOGL  138.497055
('GOOGL', 2024, 2)
         Date  Year  Month Symbol   Adj Close
42 2024-02-01  2024      2  GOOGL  140.811340
45 2024-02-02  2024      2  GOOGL  142.028320
46 2024-02-05  2024      2  GOOGL  143.325089
48 2024-02-06  2024      2  GOOGL  143.744080
51 2024-02-07  2024      2  GOOGL  145.180511
('GOOGL', 2024, 3)
         Date  Year  Month Symbol   Adj Close
82 2024-03-01  2024      3  GOOGL  136.801254
84 2024-03-04  2024      3  GOOGL  133.020630
87 2024-03-05  2024      3  GOOGL  132.342300
88 2024-03-06  2024      3  GOOGL  131.075424
91 2024-03-07  2024      3  GOOGL  134.048080
('GOOGL', 2024, 4)
          Date  Year  Month Symbol   Adj Close
122 2024-04-01  2024      4  GOOGL  155.105942
124 2024-04-02  2024      4  GOOGL  154.178223
126 2024-04-03  2024      4  GOOGL  154.537338
128 2024-04-04  2024      4  GOOGL  150.158188
131 2024-04-05  2024      4  GOOGL  152.123322
('GOOGL', 2024, 5)
          Date  Year  Month Symbol   Adj Close
167 2024-05-01  2024      5  GOOGL  163.455246
168 2024-05-02  2024      5  GOOGL  166.208435
170 2024-05-03  2024      5  GOOGL  166.826904
173 2024-05-06  2024      5  GOOGL  167.684799
174 2024-05-07  2024      5  GOOGL  170.826996
('GOOGL', 2024, 6)
          Date  Year  Month Symbol   Adj Close
210 2024-06-03  2024      6  GOOGL  172.742264
213 2024-06-04  2024      6  GOOGL  173.360718
215 2024-06-05  2024      6  GOOGL  174.976746
217 2024-06-06  2024      6  GOOGL  176.293457
218 2024-06-07  2024      6  GOOGL  174.029083
('GOOGL', 2024, 7)
          Date  Year  Month Symbol   Adj Close
248 2024-07-01  2024      7  GOOGL  182.747513
250 2024-07-02  2024      7  GOOGL  184.994522
252 2024-07-03  2024      7  GOOGL  185.573761
255 2024-07-05  2024      7  GOOGL  190.347427
257 2024-07-08  2024      7  GOOGL  188.779495
('GOOGL', 2024, 8)
          Date  Year  Month Symbol   Adj Close
293 2024-08-01  2024      8  GOOGL  170.533707
294 2024-08-02  2024      8  GOOGL  166.439148
296 2024-08-05  2024      8  GOOGL  159.038971
298 2024-08-06  2024      8  GOOGL  158.080231
301 2024-08-07  2024      8  GOOGL  158.729370

### Question 9-1. Let's set the index of the data to be the following three fields we are creating a multi-index.

In [390]:
df =\
df.set_index(['Symbol', 'Year', 'Month'])

                        Date   Adj Close
Symbol Year Month
AAPL   2024 1     2024-01-02  184.938217
GOOGL  2024 1     2024-01-02  137.828705
            1     2024-01-03  138.576859
AAPL   2024 1     2024-01-03  183.553467
            1     2024-01-04  181.222321
...                      ...         ...
            8     2024-08-28  226.490005
GOOGL  2024 8     2024-08-29  161.565613
AAPL   2024 8     2024-08-29  229.789993
            8     2024-08-30  229.000000
GOOGL  2024 8     2024-08-30  163.163498

[336 rows x 2 columns]

#### Question 9-2. Then, please group based upon values in the actual index the following groups by level 0 of the index (Month)

In [396]:
for key, item in df.groupby(['Symbol']).groups.items():
    print(key)
    print(df.loc[item].head())

AAPL
                        Date   Adj Close
Symbol Year Month
AAPL   2024 1     2024-01-02  184.938217
            1     2024-01-03  183.553467
            1     2024-01-04  181.222321
            1     2024-01-05  180.495087
            1     2024-01-08  184.858521
GOOGL
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 1     2024-01-02  137.828705
            1     2024-01-03  138.576859
            1     2024-01-04  136.053101
            1     2024-01-05  135.394745
            1     2024-01-08  138.497055

AAPL
                        Date   Adj Close
Symbol Year Month
AAPL   2024 1     2024-01-02  184.938217
            1     2024-01-03  183.553467
            1     2024-01-04  181.222321
            1     2024-01-05  180.495087
            1     2024-01-08  184.858521
GOOGL
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 1     2024-01-02  137.828705
            1     2024-01-03  138.576859
            1     2024-01-04  136.053101
            1     2024-01-05  135.394745
            1     2024-01-08  138.497055

#### Question 9-3. Please group by three levels in the index using their names

In [397]:
for key, item in df.groupby(['Symbol', 'Year', 'Month']).groups.items():
    print(key)
    print(df.loc[item].head())

('AAPL', 2024, 1)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 1     2024-01-02  184.938217
            1     2024-01-03  183.553467
            1     2024-01-04  181.222321
            1     2024-01-05  180.495087
            1     2024-01-08  184.858521
('AAPL', 2024, 2)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 2     2024-02-01  186.153625
            2     2024-02-02  185.147430
            2     2024-02-05  186.970505
            2     2024-02-06  188.584381
            2     2024-02-07  188.693970
('AAPL', 2024, 3)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 3     2024-03-01  179.209229
            3     2024-03-04  174.660660
            3     2024-03-05  169.693161
            3     2024-03-06  168.695648
            3     2024-03-07  168.575958
('AAPL', 2024, 4)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 4     2024-04-01  169.603378
            4     2024-04-02  168.416351
            4     2024-04-03  169.224319
            4     2024-04-04  168.396423
            4     2024-04-05  169.154495
('AAPL', 2024, 5)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 5     2024-05-01  168.875214
            5     2024-05-02  172.595840
            5     2024-05-03  182.919876
            5     2024-05-06  181.254089
            5     2024-05-07  181.942322
('AAPL', 2024, 6)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 6     2024-06-03  193.805664
            6     2024-06-04  194.125305
            6     2024-06-05  195.643539
            6     2024-06-06  194.255142
            6     2024-06-07  196.662369
('AAPL', 2024, 7)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 7     2024-07-01  216.499405
            7     2024-07-02  220.015335
            7     2024-07-03  221.293854
            7     2024-07-05  226.078308
            7     2024-07-08  227.556610
('AAPL', 2024, 8)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 8     2024-08-01  218.107544
            8     2024-08-02  219.605804
            8     2024-08-05  209.028061
            8     2024-08-06  206.990402
            8     2024-08-07  209.577423
('GOOGL', 2024, 1)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 1     2024-01-02  137.828705
            1     2024-01-03  138.576859
            1     2024-01-04  136.053101
            1     2024-01-05  135.394745
            1     2024-01-08  138.497055
('GOOGL', 2024, 2)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 2     2024-02-01  140.811340
            2     2024-02-02  142.028320
            2     2024-02-05  143.325089
            2     2024-02-06  143.744080
            2     2024-02-07  145.180511
('GOOGL', 2024, 3)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 3     2024-03-01  136.801254
            3     2024-03-04  133.020630
            3     2024-03-05  132.342300
            3     2024-03-06  131.075424
            3     2024-03-07  134.048080
('GOOGL', 2024, 4)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 4     2024-04-01  155.105942
            4     2024-04-02  154.178223
            4     2024-04-03  154.537338
            4     2024-04-04  150.158188
            4     2024-04-05  152.123322
('GOOGL', 2024, 5)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 5     2024-05-01  163.455246
            5     2024-05-02  166.208435
            5     2024-05-03  166.826904
            5     2024-05-06  167.684799
            5     2024-05-07  170.826996
('GOOGL', 2024, 6)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 6     2024-06-03  172.742264
            6     2024-06-04  173.360718
            6     2024-06-05  174.976746
            6     2024-06-06  176.293457
            6     2024-06-07  174.029083
('GOOGL', 2024, 7)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 7     2024-07-01  182.747513
            7     2024-07-02  184.994522
            7     2024-07-03  185.573761
            7     2024-07-05  190.347427
            7     2024-07-08  188.779495
('GOOGL', 2024, 8)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 8     2024-08-01  170.533707
            8     2024-08-02  166.439148
            8     2024-08-05  159.038971
            8     2024-08-06  158.080231
            8     2024-08-07  158.729370

('AAPL', 2024, 1)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 1     2024-01-02  184.938217
            1     2024-01-03  183.553467
            1     2024-01-04  181.222321
            1     2024-01-05  180.495087
            1     2024-01-08  184.858521
('AAPL', 2024, 2)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 2     2024-02-01  186.153625
            2     2024-02-02  185.147430
            2     2024-02-05  186.970505
            2     2024-02-06  188.584381
            2     2024-02-07  188.693970
('AAPL', 2024, 3)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 3     2024-03-01  179.209229
            3     2024-03-04  174.660660
            3     2024-03-05  169.693161
            3     2024-03-06  168.695648
            3     2024-03-07  168.575958
('AAPL', 2024, 4)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 4     2024-04-01  169.603378
            4     2024-04-02  168.416351
            4     2024-04-03  169.224319
            4     2024-04-04  168.396423
            4     2024-04-05  169.154495
('AAPL', 2024, 5)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 5     2024-05-01  168.875214
            5     2024-05-02  172.595840
            5     2024-05-03  182.919876
            5     2024-05-06  181.254089
            5     2024-05-07  181.942322
('AAPL', 2024, 6)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 6     2024-06-03  193.805664
            6     2024-06-04  194.125305
            6     2024-06-05  195.643539
            6     2024-06-06  194.255142
            6     2024-06-07  196.662369
('AAPL', 2024, 7)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 7     2024-07-01  216.499405
            7     2024-07-02  220.015335
            7     2024-07-03  221.293854
            7     2024-07-05  226.078308
            7     2024-07-08  227.556610
('AAPL', 2024, 8)
                        Date   Adj Close
Symbol Year Month
AAPL   2024 8     2024-08-01  218.107544
            8     2024-08-02  219.605804
            8     2024-08-05  209.028061
            8     2024-08-06  206.990402
            8     2024-08-07  209.577423
('GOOGL', 2024, 1)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 1     2024-01-02  137.828705
            1     2024-01-03  138.576859
            1     2024-01-04  136.053101
            1     2024-01-05  135.394745
            1     2024-01-08  138.497055
('GOOGL', 2024, 2)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 2     2024-02-01  140.811340
            2     2024-02-02  142.028320
            2     2024-02-05  143.325089
            2     2024-02-06  143.744080
            2     2024-02-07  145.180511
('GOOGL', 2024, 3)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 3     2024-03-01  136.801254
            3     2024-03-04  133.020630
            3     2024-03-05  132.342300
            3     2024-03-06  131.075424
            3     2024-03-07  134.048080
('GOOGL', 2024, 4)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 4     2024-04-01  155.105942
            4     2024-04-02  154.178223
            4     2024-04-03  154.537338
            4     2024-04-04  150.158188
            4     2024-04-05  152.123322
('GOOGL', 2024, 5)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 5     2024-05-01  163.455246
            5     2024-05-02  166.208435
            5     2024-05-03  166.826904
            5     2024-05-06  167.684799
            5     2024-05-07  170.826996
('GOOGL', 2024, 6)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 6     2024-06-03  172.742264
            6     2024-06-04  173.360718
            6     2024-06-05  174.976746
            6     2024-06-06  176.293457
            6     2024-06-07  174.029083
('GOOGL', 2024, 7)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 7     2024-07-01  182.747513
            7     2024-07-02  184.994522
            7     2024-07-03  185.573761
            7     2024-07-05  190.347427
            7     2024-07-08  188.779495
('GOOGL', 2024, 8)
                        Date   Adj Close
Symbol Year Month
GOOGL  2024 8     2024-08-01  170.533707
            8     2024-08-02  166.439148
            8     2024-08-05  159.038971
            8     2024-08-06  158.080231
            8     2024-08-07  158.729370

### <font color="green">"Thank you for putting your efforts into the exercise problem sets 💯"</font>